// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZAiSCOQJGrCnuEYCsCj33R0-v54UI6d4',
    appId: '1:732544838915:web:d05d76a0698681671a0d36',
    messagingSenderId: '732544838915',
    projectId: 'mlcms-app',
    authDomain: 'mlcms-app.firebaseapp.com',
    databaseURL: 'https://mlcms-app-default-rtdb.firebaseio.com',
    storageBucket: 'mlcms-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNTr0xtRxoDT1aCSSRhlx3IZBnLj0832A',
    appId: '1:732544838915:android:b6ae5ab73015f7901a0d36',
    messagingSenderId: '732544838915',
    projectId: 'mlcms-app',
    databaseURL: 'https://mlcms-app-default-rtdb.firebaseio.com',
    storageBucket: 'mlcms-app.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnVVVLFtiV7cnozUxDnAJokgVPGVKoDTg',
    appId: '1:732544838915:ios:9bba57e77eba12381a0d36',
    messagingSenderId: '732544838915',
    projectId: 'mlcms-app',
    databaseURL: 'https://mlcms-app-default-rtdb.firebaseio.com',
    storageBucket: 'mlcms-app.firebasestorage.app',
    iosBundleId: 'com.example.mlcmsApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnVVVLFtiV7cnozUxDnAJokgVPGVKoDTg',
    appId: '1:732544838915:ios:9bba57e77eba12381a0d36',
    messagingSenderId: '732544838915',
    projectId: 'mlcms-app',
    databaseURL: 'https://mlcms-app-default-rtdb.firebaseio.com',
    storageBucket: 'mlcms-app.firebasestorage.app',
    iosBundleId: 'com.example.mlcmsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZAiSCOQJGrCnuEYCsCj33R0-v54UI6d4',
    appId: '1:732544838915:web:f693de5ce87ec7581a0d36',
    messagingSenderId: '732544838915',
    projectId: 'mlcms-app',
    authDomain: 'mlcms-app.firebaseapp.com',
    databaseURL: 'https://mlcms-app-default-rtdb.firebaseio.com',
    storageBucket: 'mlcms-app.firebasestorage.app',
  );
}
